# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "TechnoWoman"
email: "contato@insideoutproject.com.br"
description: "Encontro de mulheres da Tecnologia."
baseurl: "/technowoman"
url: "insideoutproject.xyz/technowoman"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-68652979-1"
googleAnalyticsSiteUrl: "http://insideoutproject.xyz/technowoman/"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Insideout Project"
organizerAlternateName: "Insideout Project | Promovendo a diversidade na área tecnológica."
organizerDescription: "Insideout Project é uma organização sem fins lucrativos. Buscamos promover a diversidade na área tecnológica porque acreditamos que as mais diversas ideias e experiências contribuem para o avanço na tecnologia."
organizerEmail: "contato@insideoutproject.com.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://insideoutproject.xyz/technowoman"

# Head
metaKeywords: "woman, women, mulheres, tecnologia, steam, tech, event, programming, developers, rio"
twitterAccount: ""
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/yD2sEXxqfsssUZLn2"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Programação"}
# - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/team/", text: "Organizadoras"}
# - {permalink: "/communities/", text: "Comunidades"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 # - {link: "https://www.eventbrite.com.br/e/rio-dev-day-tickets-28344870270?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&aff=escb&utm-source=cp&utm-term=listing", text: "Participe do Evento"}
 #- {link: "https://goo.gl/forms/yD2sEXxqfsssUZLn2", text: "Seja um Palestrante"}

rightNavigationButtons:
 # - {link: "https://www.eventbrite.com.br/e/rio-dev-day-tickets-28344870270?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&aff=escb&utm-source=cp&utm-term=listing", text: "Participe do Evento"}
 #- {link: "https://goo.gl/forms/yD2sEXxqfsssUZLn2", text: "Seja um Palestrante"}


# Hero Block
heroImage: "rio-walp-light.png"
logoUnigranrio: "technowoman-logo.png"
heroTitle: "TechnoWoman - <typeout>"
eventDate: "15 de abril de 2017"
typeoutTextValues: '"Mulher", "Tecnologia", "Maternidade", "Carreira", "Networking"'
typeoutFallback: "Dia da Mulher"
heroButtons:
 #- {link: "https://goo.gl/forms/yD2sEXxqfsssUZLn2", text: "Seja um Palestrante"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Sobre o TechnoWoman"
aboutBlock:
 - {title: "Palestras", image: "bigdata.jpg", text: "Palestras sobre mercado, tecnologia e nosso papel na sociedade." }
 - {title: "Lightning Talks", image: "iot.png", text: "Pequenas apresentações de 5 minutos sobre qualquer coisa que te der na telha." }
 - {title: "Workshops", image: "dev.png", text: "Duas horas e meia de puro aprendizado com profissionais renomadas no mercado." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "", info: "participantes", detail: ""}
 - {count: "8", specialCharacter: "", info: "horas", detail: "de conteúdo"}
 - {count: "5", specialCharacter: "", info: "palestras", detail: "inspiradoras"}
 - {count: "2", specialCharacter: "", info: "workshops", detail: "incríveis"}
 - {count: "1", specialCharacter: "", info: "dia", detail: "de informação e networking"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Os Palestrantes"
rockstarSpeakersButtonText: "Ver todos os palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "IBM"
eventLocationLink: "https://www.ibm.com"
eventStreetAddress: "Av. Pasteur, 138/146 - Botafogo"
eventAddressLocality: "Estado do Rio de Janeiro"
eventAddressLocalityRegion: "Rio de Janeiro"
eventPostalCode: ""
eventAddressCountry: "Brasil"
eventStartTime: "2017-04-15T09:00"
eventDoorTime: "09:00"
eventEndTime: "2017-04-15T18:00"
eventPlaceCoordinates: "-22.9504552,-43.1793916"
mapCenterCoordinates: "-22.9504552,-43.1793916"
mapMobileCenterCoordinates: "-22.9504552,-43.1793916"

# Venue Block
venueBlockTitle: "IBM"
venueBigImage: "auditorio.jpg"
venueSmallImage1: "novaamerica.png"
venueSmallImage2: "novaamerica-2.jpg"
#venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditório"
venueFeatures: ["Bom ambiente para palestras", "Boa acústica, climatização", "Localizado dentro da Universidade", "Universidade localizada dentro de um shopping!"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "e aí?"
twitterHashTag: "technowoman"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Parceiros"

partnersC4sponsorsButton: "Seja um patrocinador, entre em contato pelo email contato@insideoutproject.com.br"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Fique por dentro!"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "O seu e-mail será guardado numa lista para que enviemos informaçõe sobre o evento"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 # - {link: "https://plus.google.com/114684774037479279638/", icon: "google-plus"}
 # - {link: "https://twitter.com/gdgcaxias", icon: "twitter"}
 - {link: "https://www.facebook.com/InsideOutProjectBrasil", icon: "facebook"}
 - {link: "https://github.com/insideoutprojectbr", icon: "github"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://insideoutproject.xyz", text: "InsideOut Project Brasil"}
   # - {link: "https://developers.google.com", text: "Google Developers"}

 -
  title: "Contatos"
  links:

   - {link: "mailto:contato@insideoutproject.com.br", text: "contato@insideoutproject.com.br"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "Quem são as voluntárias por trás do TechnoWoman?"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-22.8782071,-43.272322"
logisticsMapMobileCenterCoordinates: "-22.8782071,-43.272322"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
